#!/usr/bin/env perl

use strict;

use lib './lib';
use Environment;
use Parse;


my $filename = shift @ARGV;

open my $filehandle, "<", $filename
    or die "Could not open file $filename $!";

my $text = do { local $/; <$filehandle> };


Parse::parse $text;

