#!/usr/bin/env perl

use strict;

use lib './lib';
use Environment;
use Parse;
use Evaluate;


my $filename = shift @ARGV;

open my $filehandle, "<", $filename
    or die "Could not open file $filename $!";

my $text = do { local $/; <$filehandle> };


my $ast = Parse::parse $text;

foreach (@$ast) {
    Evaluate::evaluate $_, $Environment::global;
}

